config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do

    member do
      get :tweets
      get :likes
      get :followings
      get :followers
    end
  end
  resources :followships, only: [:create, :destroy]

  resources :tweets, only: [:index, :show, :new, :create] do

    resources :replies, only: [:index, :create, :destroy]

    member do
      post :like
      post :unlike
    end

  end

  root "tweets#index"


  namespace :admin do
    resources :tweets, only: [:index, :destroy]
    root "tweets#index"
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由
>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72

end

app/models/tweet.rb
class Tweet < ApplicationRecord
<<<<<<< HEAD
  belongs_to :user, dependent: :destroy, optional: true
  has_many :replies
  mount_uploader :image, PhotoUploader

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  default_scope -> { order('id DESC') }


=======
  validates_length_of :description, maximum: 140
>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72

end

app/controllers/admin/tweets_controller.rb
<<<<<<< HEAD
class Admin::TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
    @tweets = Tweet.all
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to admin_tweets_path
    flash[:alert] = "TWEET WAS DELETED"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:description, :image)
  end
  
=======
class Admin::TweetsController < Admin::BaseController
  def index
  end

  def destroy
  end
>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
<<<<<<< HEAD
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
    @users = User.all
    @popular = User.order(followers_count: :desc).limit(10)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = "Tweet was successfully created"
      redirect_to tweets_path
    else
      flash.now["alert"] = "Tweet was failed to create"
      render :new
    end
  end

  def like
    @tweet = Tweet.find(params[:id])
    @tweet.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    @tweet = Tweet.find(params[:id])
    likes = Like.where(tweet: @tweet, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:description)
  end
  
=======

  def index
    @users # 基於測試規格，必須講定變數名稱，請用此變數中存放關注人數 Top 10 的使用者資料
  end

  def create
  end

  def like
  end

  def unlike
  end

>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72
end

app/helpers/admin/tweets_helper.rb
module Admin::TweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <%= form_for @tweet do |f| %>
        <div class= "tweet-area">
          <%= f.text_area :description, {maxlength: 140, class: "form-control :focus", rows: "5",placeholder: "How are you today?"} %>
        </div>
        <%= f.submit 'Tweet', {class: "btn btn-primary pull-right"}%>
      <% end %>
      
      <br /> 
      <br />

      <% @tweets.each do |tweet| %>
        <%= link_to tweet_replies_path(tweet) do %>
          <div class="tweet-item">
            <div class="col-md-3">
              <div class="img-container">
                <%= image_tag tweet.user.avatar if tweet.user.avatar? %>
              </div>
            </div>
              <div class="user-date">
                <%= tweet.user.name %>,
                <%= time_ago_in_words(tweet.created_at) %>
              </div>
              <div class="tweet-index">
                <%= tweet.description %>
              </div>
              <%= link_to "Reply", tweet_replies_path(tweet) %>

              <% if tweet.is_liked?(current_user) %>
                <%= link_to unlike_tweet_path(tweet), method: :post do %>
                  <button type="button" class="btn btn-default btn-xs">
                  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Unlike
                  </button>
                <% end %>
              <% else %>
                <%= link_to like_tweet_path(tweet), method: :post do %>
                  <button type="button" class="btn btn-default btn-xs">
                  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Like 
                  </button>
                <% end %>
              <% end %>


          </div>
        <% end %>
      <% end %>

    </div>

    <div class="col-md-4">

      <div class="title">Popular</div>

      <% @popular.each do |popular| %>
        <div class="tweet-item">
          <div class="col-md-6">
            <div class="img-container">
              <%= image_tag popular.avatar if popular.avatar? %>
            </div>
          </div>
        <div class="user-date"><p>
          <%= link_to "#{popular.name}", tweets_user_path(popular) %></p>
        </div>
        <%= popular.followers_count %>
        <p><%= popular.introduction %></p>
        <% if popular != current_user %>
          <% if current_user.following?(popular)%>
            <%= link_to 'Unfollow', followship_path(popular), method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= link_to 'Follow', followships_path(following_id: popular), method: :post,class: "btn btn-primary" %>
          <% end %>
        <% end %>
        </div>

      <% end %> 

    </div>

  </div>
</div>