config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do

    member do
      get :tweets
      get :likes
      get :followings
      get :followers
    end
  end
  resources :followships, only: [:create, :destroy]

  resources :tweets, only: [:index, :show, :new, :create] do

    resources :replies, only: [:index, :create, :destroy]

    member do
      post :like
      post :unlike
    end

  end

  root "tweets#index"


  namespace :admin do
    resources :tweets, only: [:index, :destroy]
    root "tweets#index"
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由
>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72

end

app/views/shared/_author.html.erb
<div class="col-md-2">
  <div class="img-container">
    <%= image_tag @user.avatar, width: '150px' if @user.avatar? %>
  </div>
  <div class="title"><%= @user.name %></div>
  <div class="introduction"><%= @user.introduction %></div>

  <br />

  <%= link_to tweets_user_path(@user),class: "user-link" do %>
    Tweets <span class="badge"><%= @tweets.count %></span>
  <% end %>

  <%= link_to likes_user_path(@user),class: "user-link" do %>
    Like <span class="badge"><%= @likes.count %></span>
  <% end %>

  <%= link_to followings_user_path(@user),class: "user-link" do %>
    Followings <span class="badge"><%= @followings.count %></span>
  <% end %>

  <%= link_to followers_user_path(@user),class: "user-link" do %>
    Followers <span class="badge"><%= @followers.count %></span>
  <% end %>

  <br />

  <% if @user == current_user %>
    <%= link_to 'Edit Profile', edit_user_path(current_user) , class: "btn btn-primary" %>
  <% else %>
    <%= link_to 'Unfollow', followship_path(@user), method: :delete %>
    <%= link_to 'Follow', followships_path(following_id: @user), method: :post %>
  <% end %>

</div>