config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do

    member do
      get :tweets
      get :likes
      get :followings
      get :followers
    end
  end
  resources :followships, only: [:create, :destroy]

  resources :tweets, only: [:index, :show, :new, :create] do

    resources :replies, only: [:index, :create, :destroy]

    member do
      post :like
      post :unlike
    end

  end

  root "tweets#index"


  namespace :admin do
    resources :tweets, only: [:index, :destroy]
    root "tweets#index"
  end
=======
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  # 請依照專案指定規格來設定路由
>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<<<<<<< HEAD

    <!-- 導覽列 -->
    <nav class = "navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type = "button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Tweeets', root_path, {class: "navbar-brand" }%>
        </div>
      
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <% if current_user.admin? %>
                <li>
                  <%= link_to 'Admin Panel', admin_tweets_path%>
                </li>
              <% end %>
            <li>
              <%= link_to 'My Tweets', tweets_user_path(current_user)%>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- alert message -->

    <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %> 
        </div>
      </div>
    </div>
    <% end %>

    <!-- 暫時保留
    
    <% if current_user %>
    Hi, <%= current_user.name %>
      <%= link_to('登出', destroy_user_session_path, method: :delete) %>
      <%= link_to('修改密碼', edit_user_registration_path) %>
    <% else %>
      <%= link_to('註冊', new_user_registration_path) %>
      <%= link_to('登入', new_user_session_path) %>
    <% end %>

    -->

    <%= yield %>


=======
    <% if current_user %>
      <% if current_user&.admin? %>
        <li><%= link_to 'Admin Panel', admin_restaurants_path %></li>
      <% end %>
      <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
      <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
      <li><%= link_to('修改個人資料', edit_user_path(current_user)) %></li>
      <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
    <% else %>
      <li><%= link_to('註冊', new_user_registration_path) %></li>
      <li><%= link_to('登入', new_user_session_path) %></li>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
>>>>>>> 3f687d8450c1b3408c06805c3dccba381bd73b72
  </body>
</html>